- name: install docker dependencies
  vars:
    docker_dep_pkgs:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent
  apt:
    name: '{{ docker_dep_pkgs }}'
    update_cache: yes
    state: latest

- name: install docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: install docker.io repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: install docker
  vars:
    docker_pkgs:
    - docker.io
    # - docker-ce
    # - docker-ce-cli
    # - containerd.io
  apt:
    name: '{{ docker_pkgs }}'
    update_cache: yes
    state: latest

- name: 'adding current user {{ ansible_env.USER }} to group docker'
  user:
    name: '{{ ansible_env.USER }}'
    groups: docker
    append: yes