- name: install dependencies
  vars:
    docker_dep_pkgs:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  apt:
    name: '{{ docker_dep_pkgs }}'
    update_cache: yes
    state: latest

- name: install docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: install docker repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} edge'

- name: install docker
  apt:
    name: 'docker-ce'
    update_cache: yes
    state: latest

- name: add aolwas user to docker group
  user:
    name: aolwas
    groups: docker
    append: yes
