- name: download i3 keyring
  get_url:
    url: http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2017.01.02_all.deb
    dest: /tmp/sur5r-keyring_2017.01.02_all.deb

- name: install i3 keyring
  apt:
    deb: /tmp/sur5r-keyring_2017.01.02_all.deb

- name: install i3 repo
  apt_repository:
    repo: 'deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe'

- name: install i3 and associated packages (network-applet, volumeicon, etc)
  apt:
    name: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - i3
    - feh
    - network-manager-openvpn-gnome
    - volumeicon-alsa
    - pavucontrol
    - xbacklight

- name: ensure xbacklight is functional
  template:
    src: xbacklight-intel.j2
    dest: /usr/share/X11/xorg.conf.d/20-intel.conf
