#- name: download i3 keyring
#  get_url:
#    url: http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb
#    dest: /tmp/sur5r-keyring_2019.02.01_all.deb
#  when: ansible_distribution == 'Ubuntu'
#
#- name: install i3 keyring
#  apt:
#    deb: /tmp/sur5r-keyring_2019.02.01_all.deb
#  when: ansible_distribution == 'Ubuntu'
#
#- name: install i3 repo
#  apt_repository:
#    repo: 'deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe'
#  when: ansible_distribution == 'Ubuntu'

- name: install i3 and associated packages (network-applet, volumeicon, etc)
  apt:
    name: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - i3
    - feh
    - network-manager-openvpn-gnome
    - volumeicon-alsa
    - pavucontrol
    - imagemagick
    - grabc
    - i3lock
    - scrot
    - sxiv
    - xbacklight
      #    - xkill
    - build-essential
    - git
    - copyq
  when: ansible_distribution == 'Ubuntu'

- name: install i3 and associated packages (network-applet, volumeicon, etc)
  vars:
    i3_pkgs:
      - i3
      - feh
      - network-manager-applet
      - volumeicon
      - pavucontrol
      - i3lock
      - scrot
      - sxiv
      - xbacklight
      - copyq
  dnf:
    name: '{{ i3_pkgs }}'
    state: latest
  when: ansible_distribution == 'Fedora'

- name: pull i3-utils-bin git repository
  git:
    repo: 'https://github.com/aolwas/i3-utils-bin.git'
    dest: '{{ project_dir }}/i3-utils-bin'
  become: no

- name: install i3-utils bin 
  shell: "make install"
  args:
    chdir: '{{ project_dir }}/i3-utils-bin'

- name: pull i3-utils-systemd git repository
  git:
    repo: 'https://github.com/aolwas/i3-utils-systemd.git'
    dest: '{{ project_dir }}/i3-utils-systemd'
  become: no

- name: configure i3-utils systemd services
  shell: "./configure"
  args:
    chdir: '{{ project_dir }}/i3-utils-systemd'
  become: no

- name: install i3-utils systemd services
  shell: "make install"
  args:
    chdir: '{{ project_dir }}/i3-utils-systemd'

    #- name: ensure xbacklight is functional
    #  template:
    #    src: xbacklight-intel.j2
    #    dest: /usr/share/X11/xorg.conf.d/20-intel.conf
