---
- name: disable ipv6
  sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: ensure services are disabled
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: False
  with_items:
    - networking
    - systemd-resolved

- name: ensure network-manager is configured with default dns option
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    insertafter: '^\[main\]'
    line: 'dns=default'
  register: nmdnsconf
  notify:
    - restart network-manager

- name: ensure /etc/resolv.conf does not exist (and is managed by network-manager)
  file:
    path: /etc/resolv.conf
    state: absent
  when: nmdnsconf.changed
  notify:
    - restart network-manager

- name: flush handlers to recreate the resolv.conf file
  meta: flush_handlers
  when: nmdnsconf.changed

- name: Create Xorg configuration directory
  file:
    path: /etc/X11/xorg.conf.d
    state: directory

# https://wiki.archlinux.org/index.php/Libinput#Common_options
- name: Enable natural scrolling
  blockinfile:
    path: /etc/X11/xorg.conf.d/30-touchpad.conf
    create: yes
    block: |
      Section "InputClass"
          Identifier "libinput touchpad catchall"
          Driver "libinput"
          MatchIsTouchpad "on"
          MatchDevicePath "/dev/input/event*"
          Option "NaturalScrolling" "true"
          Option "ClickMethod" "clickfinger"
          Option "Tapping" "off"
          Option "DisableWhileTyping" "on"
      EndSection

- name: ensure deep sleep mode
  grub_cmdline:
    option: mem_sleep_default
    value: deep
  register: grub_update_res

- name: reboot to apply modification
  shell: sleep 2 && shutdown -r now "Reboot triggered by Ansible"
  async: 1
  poll: 0
  ignore_errors: yes
  when:
  - grub_update_res.changed

- name: wait for reboot
  become: no
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 30
    timeout: 300
  when:
  - grub_update_res.changed
