# - name: install sway repo
#   apt_repository:
#     repo: 'ppa:samoilov-lex/sway'
#     codename: 'disco'
#   when: ansible_distribution == 'Ubuntu'

- name: install sway and associated packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - sway
    - swaybg
    - mako-notifier
    - network-manager-openvpn-gnome
    - pavucontrol
    - imagemagick
    - swaylock
    - swayidle
    - wdisplays
    - waybar
    - wl-clipboard
    - brightnessctl
    - build-essential
    - git
    - grim
    - slurp
    - rofi
    - fonts-cantarell
    - fonts-noto
  when: ansible_distribution == 'Ubuntu'

- name: set setuid on brightnessctl binary
  file:
    path: /usr/bin/brightnessctl
    state: file
    mode: u+s
    modification_time: preserve
    access_time: preserve
# - name: install latest wl-clipboard version from next ubuntu distrib
#   apt:
#     deb: https://launchpad.net/ubuntu/+archive/primary/+files/wl-clipboard_2.0.0-1_amd64.deb
#     state: present
#   when: ansible_distribution == 'Ubuntu'
