- name: install sway repo
  apt_repository:
    repo: 'ppa:samoilov-lex/sway'
  when: ansible_distribution == 'Ubuntu'

- name: install sway and associated packages
  apt:
    name: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - sway
    - network-manager-openvpn-gnome
    - pavucontrol
    - imagemagick
    - swaylock
    - brightessctl
    - build-essential
    - git
    - grim
    - slurp
    - wl-clipboard
    - rofi
  when: ansible_distribution == 'Ubuntu'
