- name: install podman repo key
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/Release.key"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: install podman repo
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /"
    state: present
    filename: podman
  when: ansible_distribution == 'Ubuntu'

- name: install podman
  apt:
    name: 'podman'
    update_cache: yes
    state: latest
