- name: install albert repo key
  apt_key:
    url: https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_18.04/Release.key
    state: present

- name: install albert repo
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.04/ /
    state: present
    filename: home:manuelschneid3r

- name: install misc applications
  vars:
    app_pkgs:
    - qemu-kvm
    - libvirt-bin
    - bridge-utils
    - virt-manager
    - albert
    - ssh-askpass
    - zsh
  apt:
    name: '{{ app_pkgs }}'
    update_cache: yes
    state: latest

- name: set default shell to zsh for $USER
  user:
    name: '{{ ansible_env.USER }}'
    shell: /bin/zsh

- name: install alacritty
  apt:
    deb: https://github.com/jwilm/alacritty/releases/download/v0.2.5/Alacritty-v0.2.5_amd64.deb

# snap module will be available in ansible 2.8
# - name: install antibody
#   snap:
#     name: antibody

- name: install antibody
  shell: snap install antibody