- name: install albert repo
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.04/ /
    state: present
    filename: home:manuelschneid3r

- name: install albert repo key
  apt_key:
    url: https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_18.04/Release.key
    state: present

- name: install misc applications
  apt:
    name: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - tmux
    - qemu-kvm
    - libvirt-bin
    - ubuntu-vm-builder
    - bridge-utils
    - virt-manager
    - albert
