- name: install vagrant package
  apt:
    deb: 'https://releases.hashicorp.com/vagrant/{{vagrant_version}}/vagrant_{{vagrant_version}}_x86_64.deb'

- name: install vagrant-libvirt plugin dependencies
  apt:
    name: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - libxslt-dev
    - libxml2-dev
    - libvirt-dev
    - zlib1g-dev
    - ruby-dev
    - ruby-libvirt
    - qemu
    - libvirt-bin
    - ebtables
    - dnsmasq
    - build-essential

- name: install vagrant-libvirt plugin
  become: no
  shell: vagrant plugin install vagrant-libvirt
  environment:
    CONFIGURE_ARGS: "with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib"
