# based on https://github.com/azavea/ansible-golang
- name: Download Go
  get_url: 
    url: "https://storage.googleapis.com/golang/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz"
    dest: "/usr/local/src/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz"

- name: Extract and install Go
  unarchive: 
    src: "/usr/local/src/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz"
    dest: /usr/local/
    copy: no

- name: Install Godep
  command: /usr/local/go/bin/go get -u github.com/tools/godep
  args:
    creates: "{{ golang_path }}/bin/godep"
  environment:
    GOPATH: "{{ golang_path }}"
