# Based on https://github.com/veggiemonk/ansible-ohmyzsh
- name: Installing Zsh and git
  apt: 
    name: '{{ item  }}'
    state: latest
    update_cache: yes
  with_items:
    - zsh
    - git
  register: installation
  tags:
    - ohmyzsh

- name: Backing up existing ~/.zshrc
  become: no
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.orig; fi
  when: installation|success
  tags:
    - ohmyzsh

- name: Cloning  oh-my-zsh
  become: no
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh'
  when: installation|success
  register: cloning
  tags:
    - ohmyzsh

- name: Creating new ~/.zshrc
  become: no
  copy:
    src: '{{ ansible_env.HOME }}/.oh-my-zsh/templates/zshrc.zsh-template'
    dest: '{{ ansible_env.HOME }}/.zshrc'
  when: cloning|success
  tags:
    - ohmyzsh

- name: install bullet-train theme
  become: no
  get_url:
    url: http://raw.github.com/caiogondim/bullet-train-oh-my-zsh-theme/master/bullet-train.zsh-theme
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/themes/bullet-train.zsh-theme'
  when: cloning|success
  tags:
    - ohmyzsh

- name: apply node prompt error patch
  become: no
  patch:
    src: bullettrain.patch
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/themes/bullet-train.zsh-theme'
  when: cloning|success
  tags:
    - ohmyzsh

- name: set default shell to zsh for $USER
  user:
    name: '{{ ansible_env.USER }}'
    shell: /bin/zsh
  when: installation|success
  tags:
    - ohmyzsh
