# Based on https://github.com/veggiemonk/ansible-ohmyzsh
- name: Installing Zsh and git
  apt:
    name: '{{ item  }}'
    state: latest
    update_cache: yes
  with_items:
    - zsh
    - git
    - fonts-powerline
    - fonts-font-awesome
  register: installation

- name: Backing up existing ~/.zshrc
  become: no
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.orig; fi
  when: installation is success

- name: Cloning  oh-my-zsh
  become: no
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh'
  when: installation is success
  register: cloning

- name: Creating new ~/.zshrc
  become: no
  copy:
    src: '{{ ansible_env.HOME }}/.oh-my-zsh/templates/zshrc.zsh-template'
    dest: '{{ ansible_env.HOME }}/.zshrc'
  when: cloning is success

- name: ensure custom theme directory exists
  become: no
  file:
    path: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes'
    state: directory
  when: cloning is success

- name: install spaceship theme
  become: no
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship-prompt'
  when: cloning is success

- name: create spaceship symlink
  become: no
  file:
    path: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme'
    src: '{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme'
    state: link
  when: cloning is success

- name: set default shell to zsh for $USER
  user:
    name: '{{ ansible_env.USER }}'
    shell: /bin/zsh
  when: installation is success
