- name: pull dotfiles git repository
  git:
    repo: 'https://github.com/aolwas/configs.git'
    dest: '{{ project_dir }}/configs'

- name: remove original config files or link if exist
  file:
    path: '{{ ansible_env.HOME }}/{{ item }}'
    state: absent
  ignore_errors: yes
  with_items:
    - '.config/i3'
    - '.config/powerline'
    - '.config/termite'
    - '.vimrc'
    - '.zshrc'

- name: create symlinks
  file:
    src: '{{ project_dir }}/configs/{{ item.src }}'
    path: '{{ ansible_env.HOME }}/{{ item.dest }}'
    state: link
  with_items:
    - { src: 'i3', dest: '.config/i3' }
    - { src: 'powerline', dest: '.config/powerline' }
    - { src: 'vimrc/vimrc', dest: '.vimrc' }
    - { src: 'zsh/zshrc', dest: '.zshrc' }
    - { src: 'termite', dest: '.config/termite'}
