- name: pull dotfiles git repository
  git:
    repo: 'https://github.com/aolwas/configs.git'
    dest: '{{ project_dir }}/configs'
  ignore_errors: yes

- name: remove original config files or link if exist
  file:
    path: '{{ ansible_env.HOME }}/{{ item }}'
    state: absent
  ignore_errors: yes
  with_items:
    - '.config/i3'
    - '.config/powerline'
    - '.config/termite'
    - '.config/alacritty'
    - '.vimrc'
    - '.zshrc'
    - '.zsh_plugins.txt'
    - '.local/share/applications/Alacritty.desktop'
    - '.tmux.conf'

- name: create symlinks
  file:
    src: '{{ project_dir }}/configs/{{ item.src }}'
    path: '{{ ansible_env.HOME }}/{{ item.dest }}'
    state: link
  with_items:
    - { src: 'i3', dest: '.config/i3' }
    # - { src: 'powerline', dest: '.config/powerline' }
    # - { src: 'vimrc/vimrc', dest: '.vimrc' }
    - { src: 'zsh/config/zshrc', dest: '.zshrc' }
    - { src: 'zsh/config/zsh_plugins.txt', dest: '.zsh_plugins.txt' }
    # - { src: 'termite', dest: '.config/termite'}
    # - { src: 'tmux/tmux.conf', dest: '.tmux.conf' }
    - { src: 'alacritty/config', dest: '.config/alacritty' }
    - { src: 'alacritty/desktop/Alacritty.desktop', dest: '.local/share/applications/Alacritty.desktop' }
