- name: install apt key
  become: yes
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80 
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
- name: install repository
  become: yes
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main
    state: present
- name: update apt cache
  become: yes
  apt:
    update_cache: yes
- name: install docker
  become: yes
  apt:
    name: "{{ item }}" 
    state: present
  with_items:
   - docker-engine
- name: install docker-compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: a+x