---
- name: Clone repo
  become: no
  git: repo=https://github.com/greshake/i3status-rust
       accept_hostkey=true
       dest='{{ project_dir }}/i3status-rust'

- name: Install dependencies
  apt: name={{item}}
       state=present
  with_items:
  - libdbus-1-dev

- name: build i3status-rust
  become: no
  shell: cargo build --release
  args:
    chdir: '{{ project_dir }}/i3status-rust'
    creates: '{{ project_dir }}/target/release/i3status-rs'
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "/home/linuxbrew/.linuxbrew/lib:{{ ansible_env.LD_LIBRARY_PATH | default('') }}"
  
- name: Install i3status-rust
  become: no
  copy:
    src: '{{ project_dir }}/target/release/i3status-rs'
    dest: '{{ ansible_env.HOME}}/bin/i3status-rust'
    remote_src: yes
    mode: 0744

