---
- name: Clone repo
  become: no
  git:
    repo: https://github.com/greshake/i3status-rust
    accept_hostkey: true
    dest: '{{ project_dir }}/i3status-rust'

- name: Install dependencies
  vars:
    i3status_pkgs:
      - libdbus-1-dev
      - fonts-font-awesome
  apt:
    name: "{{ i3status_pkgs }}"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install dependencies
  vars:
    i3status_pkgs:
      - dbus-devel
      - fontawesome-fonts
  dnf:
    name: '{{ i3status_pkgs }}'
    state: present
  when: ansible_distribution == 'Fedora'

- name: build i3status-rust
  become: no
  shell: "cargo build --release"
  args:
    executable: /bin/bash
    chdir: '{{ project_dir }}/i3status-rust'
    creates: '{{ project_dir }}/target/release/i3status-rs'
  environment:
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
    PKG_CONFIG_PATH: "/usr/lib/x86_64-linux-gnu/pkgconfig:{{ ansible_env.PKG_CONFIG_PATH | default('') }}"

- name: Install i3status-rust
  copy:
    src: '{{ project_dir }}/i3status-rust/target/release/i3status-rs'
    dest: '/usr/local/bin/i3status-rs'
    remote_src: yes
    mode: 0755

