---
- name: Install dependencies of Linuxbrew
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - gcc-4.8
    - curl
    - git
    - m4
    - ruby
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - zlib1g-dev
      # if needed for alacritty install
    - cmake
    - libfreetype6-dev
    - libfontconfig1-dev
    - xclip

- name: Install Linuxbrew
  git:
    repo: https://github.com/Linuxbrew/brew.git
    dest: "{{ ansible_env.HOME }}/.linuxbrew"
  become: no

- name: Install brew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
  - go
  - dep
  - fzf
  - ag
  - kubernetes-cli
  - kubectx
  - kubernetes-helm
  - ranger
  - vault
  - terraform
  - bitwarden-cli
  environment:
    PATH: "{{ ansible_env.HOME }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ ansible_env.HOME }}/.linuxbrew/lib:{{ ansible_env.LD_LIBRARY_PATH }}"
  become: no

- name: fzf post install
  shell: "{{ ansible_env.HOME }}/.linuxbrew/opt/fzf/install --all"
  environment:
    PATH: "{{ ansible_env.HOME }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ ansible_env.HOME }}/.linuxbrew/lib:{{ ansible_env.LD_LIBRARY_PATH }}"
  become: no
