---
- name: Install dependencies of Linuxbrew
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - gcc-4.8
    - curl
    - git
    - m4
    - ruby
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - zlib1g-dev

- name: Install Linuxbrew
  git:
    repo: https://github.com/Linuxbrew/brew.git
    dest: "{{ ansible_env.HOME }}/.linuxbrew"
  become: no

  #- name: Tap homebrew/extra
  #  shell: brew tap homebrew/extra
  #  environment:
  #    PATH: "{{ ansible_env.HOME }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
  #  become: no

- name: Install brew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
  - go
  - fzf
  - neovim
  environment:
    PATH: "{{ ansible_home }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ ansible_home}}/.linuxbrew/lib:{{ ansible_env.LD_LIBRARY_PATH }}"
  become: no

- name: fzf post install
  shell: "{{ ansible_env.HOME }}/.linuxbrew/opt/fzf/install"
  environment:
    PATH: "{{ ansible_home }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ ansible_home}}/.linuxbrew/lib:{{ ansible_env.LD_LIBRARY_PATH }}"
  become: no
