---
- name: Install dependencies of Linuxbrew
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - gcc-4.8
    - curl
    - git
    - m4
    - ruby
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - zlib1g-dev

- name: Install Linuxbrew
  git:
    repo: https://github.com/Linuxbrew/brew.git
    dest: "{{ ansible_env.HOME }}/.linuxbrew"
  become: no

- name: Install brew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
  - go
  - rustup
  - fzf
  - kubernetes-cli
  - kubectx
  - kubernetes-helm
  - ranger
  - vault
  - terraform
  environment:
    PATH: "{{ ansible_home }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ ansible_home}}/.linuxbrew/lib:{{ ansible_env.LD_LIBRARY_PATH }}"
  become: no

- name: rustup post install
  shell: "rustup-init -y"
  environment:
    PATH: "{{ ansible_home }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ ansible_home}}/.linuxbrew/lib:{{ ansible_env.LD_LIBRARY_PATH }}"
  become: no

- name: fzf post install
  shell: "{{ ansible_env.HOME }}/.linuxbrew/opt/fzf/install"
  environment:
    PATH: "{{ ansible_home }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ ansible_home}}/.linuxbrew/lib:{{ ansible_env.LD_LIBRARY_PATH }}"
  become: no

- name: Install rust based brew packages
  homebrew:
    name: "{{ item }}"
    state: head
  with_items:
  - aolwas/homebrew-tap/alacritty
  environment:
    PATH: "{{ ansible_home }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ ansible_home}}/.linuxbrew/lib:{{ ansible_env.LD_LIBRARY_PATH }}"
  become: no
