---
- name: Install dependencies of Linuxbrew
  vars:
    lb_dep_pkgs:
    - build-essential
    - gcc-4.8
    - curl
    - git
    - m4
    - ruby
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - zlib1g-dev
      # if needed for alacritty install
    - cmake
    - libfreetype6-dev
    - libfontconfig1-dev
    - xclip
  apt:
    name: "{{ lb_dep_pkgs }}"
    state: present

- name: Ensure /home/linuxbrew exists
  file:
    path: /home/linuxbrew
    state: directory
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"

- name: Install Linuxbrew
  git:
    repo: https://github.com/Homebrew/brew
    dest: /home/linuxbrew/.linuxbrew
  become: no

- name: Install brew packages
  vars:
    lb_pkgs:
    - go
    - dep
    - rustup-init
    - fzf
    - ag
    - kubernetes-cli
    - kubectx
    - kubernetes-helm
    - stern
    - vault
    - terraform
    - gpg2
    - direnv
  homebrew:
    name: "{{ lb_pkgs }}"
    state: present
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "/home/linuxbrew/.linuxbrew/lib:{{ ansible_env.LD_LIBRARY_PATH | default('') }}"
  become: no

- name: fzf post install
  shell: "/home/linuxbrew/.linuxbrew/opt/fzf/install --all"
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "/home/linuxbrew/.linuxbrew/lib:{{ ansible_env.LD_LIBRARY_PATH | default('') }}"
  become: no
